# 1. Install docker and docker-compose on a staging server;
# 2. On the staging server, create a folder ratos3 and copy there docker-compose.yaml and create folders database, sql and redis inside it;
# 2.1 On the staging server, put sql scripts to init the DB into folder sql (docker will execute all the files with .sql extension);
# 3. Being inside folder ratos3 invoke the following command:
#     docker-compose up -d
# 4. App is up. Done.

version: '3.1'

services:

  ratos_db:
    container_name: ratos_db
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ratos3
      - MYSQL_USER=spring
      - MYSQL_PASSWORD=spring
    volumes:
      - ./database:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

  redis_db:
    container_name: redis_db
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]

  ratos_app:
    container_name: ratos_app
    depends_on:
      - ratos_db
      - redis_db
    image: gelever85/ratos3:redis
    restart: always
    ports:
      - "80:8080"
    environment:
      - DATABASE_HOST=ratos_db
      - DATABASE_USER=spring
      - DATABASE_PASSWORD=spring
      - DATABASE_NAME=ratos3
      - DATABASE_PORT=3306
      - REDIS_HOST=redis_db
      - REDIS_SECRET=spring
      - REDIS_PORT=6379
      - LTI_LAUNCH_URL=http://456.145.74.85:80/lti/1p0/launch
    volumes:
      - ./logs:/logs
