server:
  port: 8090
  servlet:
    session:
      timeout: 200m
  tomcat:
    max-threads: 200

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ratos3?rewriteBatchedStatements=true&useSSL=false
    username: spring
    password: sP3gxP2V
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    properties:
      hibernate:
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
          javax.cache.provider: org.ehcache.jsr107.EhcacheCachingProvider
        javax.persistence.sharedCache.mode: ENABLE_SELECTIVE
        javax.cache.uri: classpath:ehcache.xml
        show_sql: false
        format_sql: true
        generate_statistics: false
  cache:
    type: caffeine
    cache-names: question
    caffeine:
      spec: maximumSize=10000,expireAfterAccess=1d
  session:
    store-type: none
    jdbc:
      cleanup-cron: "0 * * * * *"
      initialize-schema: embedded
      schema: classpath:org/springframework/session/jdbc/schema-mysql.sql
      table-name: SPRING_SESSION
    redis:
      cleanup-cron: "0 * * * * *"
      flush-mode: on_save
      namespace: spring:session
  redis:
    host: localhost
    port: 6379

ratos:
  init:
    re_init: false
    populate: false
    cache: NONE
    cache_threads: 4
  session:
    include_groups: true
    shuffle_enabled: true
    random_algorithm: CACHED
    preserved_limit: 5
    starred_limit: 100
    save_timeouted_results: true
    save_cancelled_results: false
    save_abandoned_results: true
    timeout_penalty: 50
    tiemout_leeway: 3
  result:
    clean_on: true
    period: DAILY
    clean_hour: 23
    clean_minute: 59
  security:
    lms-registration: true
    non-lms-registration: true
  lti:
    launch_url: http://localhost:8090/lti/1p0/launch
    launch_path: /lti/1p0/launch
    launch_url_fix: true