server:
  port: ${SERVER_PORT}
  servlet:
    context-path: /api
    session:
      timeout: ${SERVLET_SESSION_TIMEOUT}
  tomcat:
    threads:
      max: ${TOMCAT_MAX_THREADS}

spring:
  application:
    name: ratos
  profiles:
    active: ${SPRING_ACTIVE_PROFILE} # For logging settings (see logback-spring.xml)
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        cache:
          use_second_level_cache: ${HIBERNATE_ENABLE_2LC:false}
          use_query_cache: ${HIBERNATE_ENABLE_2LC:false}
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
          jakarta:
            cache:
              provider: org.ehcache.jsr107.EhcacheCachingProvider
        jakarta:
          cache:
            uri: classpath:ehcache.xml
      jakarta:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      indent_output: true
  quartz:
    job-store-type: memory
    properties:
      org.quartz.threadPool.threadCount: 4
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 30d
  cache:
    type: ${SPRING_CACHE_TYPE}
    cache-names: question
    caffeine:
      spec: maximumSize=10000,expireAfterAccess=1d
  session:
    redis:
      cleanup-cron: "59 59 23 * * *"
      repository-type: indexed
      flush-mode: on_save
      namespace: spring:session
  data:
    redis:
      host: ${REDIS_HOST}
      password: ${REDIS_SECRET}
      port: ${REDIS_PORT}
  flyway:
    enabled: true
    clean-disabled: false
    locations:
    - classpath:db/migration/database
    - classpath:db/migration/defaults

management:
  health:
    redis:
      enabled: false

ratos:
  init:
    populate: false
    cache: ${RATOS_INIT_CACHE}
    cache_threads: ${RATOS_INIT_CACHE_THREADS}
  session:
    include_groups: ${RATOS_SESSION_INCLUDE_GROUPS}
    shuffle_enabled: ${RATOS_SESSION_SHUFFLE_ENABLED}
    random_algorithm: ${RATOS_SESSION_RANDOM_ALGORITHM}
    preserved_limit: ${RATOS_SESSION_PRESERVED_LIMIT}
    starred_limit: ${RATOS_SESSION_STARRED_LIMIT}
    save_timeouted_results: ${RATOS_SESSION_SAVE_TIMEOUTED_RESULTS}
    save_cancelled_results: ${RATOS_SESSION_SAVE_CANCELLED_RESULTS}
    save_abandoned_results: ${RATOS_SESSION_SAVE_ABANDONED_RESULTS}
    timeout_penalty: ${RATOS_SESSION_TIMEOUT_PENALTY}
    tiemout_leeway: ${RATOS_SESSION_TIMEOUT_LEEWAY}
  game:
    game_on: false
    low_boundary_from: 80.0
    low_boundary_to: 84.99
    middle_boundary_from: 85.0
    middle_boundary_to: 94.99
    high_boundary_from: 95.0
    high_boundary_to: 100.0
    low_boundary_points: 1
    middle_boundary_points: 3
    high_boundary_points: 5
    bonus_strike: 3
    bonus_size: 10
    top_weekly: 10
    reset_weekly_day: SUNDAY
    reset_weekly_hour: 23
    reset_weekly_minute: 59
    user_label:
      0: Novice
      1: Beginner
      2: Smart
      3: Mature
      5: Professional
      20: Expert
      100: Genius
    process_timeouted_results: true
    process_cancelled_results: true
  result:
    clean_on: ${RATOS_RESULT_CLEAN_ON}
    period: ${RATOS_RESULT_PERIOD}
    clean_hour: 23
    clean_minute: 59
  security:
    lms-registration: ${RATOS_SECURITY_LMS_REGISTRATION}
    non-lms-registration: ${RATOS_SECURITY_NON_LMS_REGISTRATION}
  lti:
    launch_url: ${RATOS_LTI_LAUNCH_URL}
    launch_path: /lti/1p0/launch
    launch_url_fix: ${RATOS_LTI_LAUNCH_URL_FIX}